export const PLAYER_STATES = {};
	PLAYER_STATES.WAITING = 0;
		
	PLAYER_STATES.ENTERING_NAME= 1;
	PLAYER_STATES.NAME_REVIEW= 2;
	PLAYER_STATES.NAME_ACCEPTED= 3;
		
	PLAYER_STATES.ANSWERING_QUESTION= 20;
	PLAYER_STATES.ANSWER_SUBMITTED= 21;
	PLAYER_STATES.RECIEVE_GRADE= 25;
		
	PLAYER_STATES.RECEIVE_SCORESHEET= 30;