// destinations
export const DESTINATION = {};
	DESTINATION.EVERYONE= 0;
    DESTINATION.PLAYERS= 1;
    DESTINATION.PLAYER= 2;
    DESTINATION.GAME_MASTER= 3;
    DESTINATION.SCOREBOARDS= 4;
    DESTINATION.SCOREBOARD= 5;

// origins
export const ORIGIN = {};
	ORIGIN.PLAYER = 2;
    ORIGIN.GAME_MASTER = 3;
    ORIGIN.SCOREBOARD = 5;

// roles
export const ROLE = {};
	ROLE.PLAYER= 0;
    ROLE.GAME_MASTER= 1;
    ROLE.SCOREBOARD= 2;
	ROLE.SERVER= 3;

// actions
export const ACTION= {};
	ACTION.ENTER_GAME= 0;
	ACTION.CONFIRM_NAME= 1;
	ACTION.DENY_NAME= 2;
	ACTION.GET_CONNECTIONS= 3;
	ACTION.RETURN_CONNECTIONS= 4;
    ACTION.SEND_QUESTION= 10;
    ACTION.SEND_ANSWER= 11;
